name: generate_code
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.2.7 #需要包含代码自动库
  annotations:
    path: ../annotations

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  generate:
    path: ../generate